/**
 * NeuroSathi Language Capabilities Matrix
 * Defines comprehensive capabilities for all 46 supported languages.
 * Distinguishes Direct Gemini Support, Translation-Based Support, and Speech Tiers.
 */

import { LANGUAGES_LIST } from "./languages";

export interface LanguageCapability {
  code: string;
  name: string;
  nativeName: string;
  speechCode: string;
  uiSupported: boolean;
  geminiDirect: boolean;
  translationSupported: boolean;
  speechToTextSupported: boolean;
  textToSpeechSupported: boolean;
  tier: "direct" | "translation" | "limited" | "none";
  family?: string;
  notes?: string;
}

export const LANGUAGE_CAPABILITIES: Record<string, LanguageCapability> = {
  // --- Indian Official Languages (Eighth Schedule + Regional) ---
  en: {
    code: "en",
    name: "English",
    nativeName: "English",
    speechCode: "en-US",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
    family: "Indo-European (Germanic)",
  },
  hi: {
    code: "hi",
    name: "Hindi",
    nativeName: "हिन्दी",
    speechCode: "hi-IN",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
    family: "Indo-Aryan",
  },
  as: {
    code: "as",
    name: "Assamese",
    nativeName: "অসমীয়া",
    speechCode: "as-IN",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: false,
    tier: "direct",
    family: "Indo-Aryan",
    notes: "Gemini native understanding and generation. Limited browser TTS availability.",
  },
  bn: {
    code: "bn",
    name: "Bengali",
    nativeName: "বাংলা",
    speechCode: "bn-IN",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
    family: "Indo-Aryan",
  },
  bho: {
    code: "bho",
    name: "Bhojpuri",
    nativeName: "भोजपुरी",
    speechCode: "hi-IN",
    uiSupported: false,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
    family: "Indo-Aryan (Bihari)",
    notes: "Native Devanagari script generation and semantic understanding.",
  },
  mai: {
    code: "mai",
    name: "Maithili",
    nativeName: "मैथिली",
    speechCode: "hi-IN",
    uiSupported: false,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
    family: "Indo-Aryan (Bihari)",
    notes: "Eighth Schedule language with Devanagari script support.",
  },
  kok: {
    code: "kok",
    name: "Konkani",
    nativeName: "कोंकणी",
    speechCode: "mr-IN",
    uiSupported: false,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
    family: "Indo-Aryan",
  },
  sa: {
    code: "sa",
    name: "Sanskrit",
    nativeName: "संस्कृतम्",
    speechCode: "hi-IN",
    uiSupported: false,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
    family: "Indo-Aryan (Classical)",
  },
  kas: {
    code: "kas",
    name: "Kashmiri",
    nativeName: "कॉशुर / कश्मीरी",
    speechCode: "hi-IN",
    uiSupported: false,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
    family: "Dardic",
  },
  brx: {
    code: "brx",
    name: "Bodo",
    nativeName: "बड़ो",
    speechCode: "hi-IN",
    uiSupported: true,
    geminiDirect: false,
    translationSupported: true,
    speechToTextSupported: false,
    textToSpeechSupported: false,
    tier: "translation",
    family: "Tibeto-Burman",
    notes: "Requires cross-lingual context prompting; speech uses regional fallback.",
  },
  doi: {
    code: "doi",
    name: "Dogri",
    nativeName: "डोगरी",
    speechCode: "hi-IN",
    uiSupported: true,
    geminiDirect: false,
    translationSupported: true,
    speechToTextSupported: false,
    textToSpeechSupported: false,
    tier: "translation",
    family: "Indo-Aryan",
    notes: "Devanagari script support via translation-assisted prompt layer.",
  },
  gu: {
    code: "gu",
    name: "Gujarati",
    nativeName: "ગુજરાતી",
    speechCode: "gu-IN",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
    family: "Indo-Aryan",
  },
  kn: {
    code: "kn",
    name: "Kannada",
    nativeName: "ಕನ್ನಡ",
    speechCode: "kn-IN",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
    family: "Dravidian",
  },
  ks: {
    code: "ks",
    name: "Kashmiri",
    nativeName: "कॉशुर / کٲشُر",
    speechCode: "ur-IN",
    uiSupported: true,
    geminiDirect: false,
    translationSupported: true,
    speechToTextSupported: false,
    textToSpeechSupported: false,
    tier: "translation",
    family: "Dardic",
    notes: "Perso-Arabic and Devanagari translation bridging.",
  },
  gom: {
    code: "gom",
    name: "Konkani",
    nativeName: "कोंकणी",
    speechCode: "mr-IN",
    uiSupported: true,
    geminiDirect: false,
    translationSupported: true,
    speechToTextSupported: false,
    textToSpeechSupported: false,
    tier: "translation",
    family: "Indo-Aryan",
    notes: "Devanagari script with Marathi-assisted linguistic bridge.",
  },
  ml: {
    code: "ml",
    name: "Malayalam",
    nativeName: "മലയാളം",
    speechCode: "ml-IN",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
    family: "Dravidian",
  },
  mni: {
    code: "mni",
    name: "Manipuri",
    nativeName: "ꯃꯤꯇꯩꯂꯣꯟ / মণিপুরী",
    speechCode: "hi-IN",
    uiSupported: true,
    geminiDirect: false,
    translationSupported: true,
    speechToTextSupported: false,
    textToSpeechSupported: false,
    tier: "translation",
    family: "Tibeto-Burman",
    notes: "Meitei Mayek and Bengali scripts handled via translation layer.",
  },
  mr: {
    code: "mr",
    name: "Marathi",
    nativeName: "मराठी",
    speechCode: "mr-IN",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
    family: "Indo-Aryan",
  },
  ne: {
    code: "ne",
    name: "Nepali",
    nativeName: "नेपाली",
    speechCode: "ne-NP",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
    family: "Indo-Aryan",
  },
  or: {
    code: "or",
    name: "Odia",
    nativeName: "ଓଡ଼ିଆ",
    speechCode: "or-IN",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: false,
    tier: "direct",
    family: "Indo-Aryan",
    notes: "Direct Gemini generation. Device TTS availability varies.",
  },
  pa: {
    code: "pa",
    name: "Punjabi",
    nativeName: "ਪੰਜਾਬੀ",
    speechCode: "pa-IN",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
    family: "Indo-Aryan",
  },
  sat: {
    code: "sat",
    name: "Santali",
    nativeName: "ᱥᱟᱱᱛᱟᱲᱤ",
    speechCode: "hi-IN",
    uiSupported: true,
    geminiDirect: false,
    translationSupported: true,
    speechToTextSupported: false,
    textToSpeechSupported: false,
    tier: "translation",
    family: "Austroasiatic",
    notes: "Ol Chiki script with translation bridge.",
  },
  sd: {
    code: "sd",
    name: "Sindhi",
    nativeName: "سنڌي / सिन्धी",
    speechCode: "ur-IN",
    uiSupported: true,
    geminiDirect: false,
    translationSupported: true,
    speechToTextSupported: false,
    textToSpeechSupported: false,
    tier: "translation",
    family: "Indo-Aryan",
  },
  ta: {
    code: "ta",
    name: "Tamil",
    nativeName: "தமிழ்",
    speechCode: "ta-IN",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
    family: "Dravidian",
  },
  te: {
    code: "te",
    name: "Telugu",
    nativeName: "తెలుగు",
    speechCode: "te-IN",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
    family: "Dravidian",
  },
  ur: {
    code: "ur",
    name: "Urdu",
    nativeName: "اردو",
    speechCode: "ur-PK",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
    family: "Indo-Aryan",
  },

  // --- Major International Languages ---
  ar: {
    code: "ar",
    name: "Arabic",
    nativeName: "العربية",
    speechCode: "ar-SA",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  "zh-CN": {
    code: "zh-CN",
    name: "Chinese (Simplified)",
    nativeName: "简体中文",
    speechCode: "zh-CN",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  "zh-TW": {
    code: "zh-TW",
    name: "Chinese (Traditional)",
    nativeName: "繁體中文",
    speechCode: "zh-TW",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  nl: {
    code: "nl",
    name: "Dutch",
    nativeName: "Nederlands",
    speechCode: "nl-NL",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  fr: {
    code: "fr",
    name: "French",
    nativeName: "Français",
    speechCode: "fr-FR",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  de: {
    code: "de",
    name: "German",
    nativeName: "Deutsch",
    speechCode: "de-DE",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  el: {
    code: "el",
    name: "Greek",
    nativeName: "Ελληνικά",
    speechCode: "el-GR",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  he: {
    code: "he",
    name: "Hebrew",
    nativeName: "עברית",
    speechCode: "he-IL",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  id: {
    code: "id",
    name: "Indonesian",
    nativeName: "Bahasa Indonesia",
    speechCode: "id-ID",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  it: {
    code: "it",
    name: "Italian",
    nativeName: "Italiano",
    speechCode: "it-IT",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  ja: {
    code: "ja",
    name: "Japanese",
    nativeName: "日本語",
    speechCode: "ja-JP",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  ko: {
    code: "ko",
    name: "Korean",
    nativeName: "한국어",
    speechCode: "ko-KR",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  fa: {
    code: "fa",
    name: "Persian",
    nativeName: "فارسی",
    speechCode: "fa-IR",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  pl: {
    code: "pl",
    name: "Polish",
    nativeName: "Polski",
    speechCode: "pl-PL",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  pt: {
    code: "pt",
    name: "Portuguese",
    nativeName: "Português",
    speechCode: "pt-BR",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  ru: {
    code: "ru",
    name: "Russian",
    nativeName: "Русский",
    speechCode: "ru-RU",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  es: {
    code: "es",
    name: "Spanish",
    nativeName: "Español",
    speechCode: "es-ES",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  sw: {
    code: "sw",
    name: "Swahili",
    nativeName: "Kiswahili",
    speechCode: "sw-KE",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  sv: {
    code: "sv",
    name: "Swedish",
    nativeName: "Svenska",
    speechCode: "sv-SE",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  th: {
    code: "th",
    name: "Thai",
    nativeName: "ไทย",
    speechCode: "th-TH",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  tr: {
    code: "tr",
    name: "Turkish",
    nativeName: "Türkçe",
    speechCode: "tr-TR",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  uk: {
    code: "uk",
    name: "Ukrainian",
    nativeName: "Українська",
    speechCode: "uk-UA",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
  vi: {
    code: "vi",
    name: "Vietnamese",
    nativeName: "Tiếng Việt",
    speechCode: "vi-VN",
    uiSupported: true,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  },
};

/**
 * Normalizes any language code, name, or native name to the standard LanguageCapability
 */
export function getLanguageCapability(identifier?: string | null): LanguageCapability {
  if (!identifier) return LANGUAGE_CAPABILITIES["en"];
  const trimmed = identifier.trim().toLowerCase();

  // Direct code match
  if (LANGUAGE_CAPABILITIES[trimmed]) {
    return LANGUAGE_CAPABILITIES[trimmed];
  }

  // Find by name, nativeName, speechCode in capabilities matrix
  const found = Object.values(LANGUAGE_CAPABILITIES).find(
    (cap) =>
      cap.code.toLowerCase() === trimmed ||
      cap.name.toLowerCase() === trimmed ||
      cap.nativeName.toLowerCase() === trimmed ||
      cap.speechCode.toLowerCase() === trimmed
  );

  if (found) return found;

  // Check 46 regional languages list
  const foundInList = LANGUAGES_LIST.find(
    (l) =>
      l.code.toLowerCase() === trimmed ||
      l.name.toLowerCase() === trimmed ||
      l.nativeName.toLowerCase() === trimmed
  );

  if (foundInList) {
    return {
      code: foundInList.code,
      name: foundInList.name,
      nativeName: foundInList.nativeName,
      speechCode: foundInList.speechCode || "en-IN",
      uiSupported: true,
      geminiDirect: true,
      translationSupported: true,
      speechToTextSupported: true,
      textToSpeechSupported: true,
      tier: "direct",
    };
  }

  // Universal dynamic capability: Never force unknown languages to English or Hindi
  const prettyName = identifier.charAt(0).toUpperCase() + identifier.slice(1);
  return {
    code: trimmed.length <= 4 ? trimmed : trimmed.slice(0, 3),
    name: prettyName,
    nativeName: prettyName,
    speechCode: "en-US",
    uiSupported: false,
    geminiDirect: true,
    translationSupported: true,
    speechToTextSupported: true,
    textToSpeechSupported: true,
    tier: "direct",
  };
}

export function getDirectGeminiLanguages(): LanguageCapability[] {
  return Object.values(LANGUAGE_CAPABILITIES).filter((c) => c.geminiDirect);
}

export function getTranslationSupportedLanguages(): LanguageCapability[] {
  return Object.values(LANGUAGE_CAPABILITIES).filter((c) => !c.geminiDirect && c.translationSupported);
}

export function getSpeechSupportedLanguages(): LanguageCapability[] {
  return Object.values(LANGUAGE_CAPABILITIES).filter((c) => c.speechToTextSupported);
}
