import { LanguageDefinition } from "../types";

/**
 * Exactly 46 curated UI selector languages arranged in STRICT ALPHABETICAL ORDER.
 * NOTE: The AI companion supports all of these plus any additional regional/world
 * languages without restriction via the AI language capabilities matrix.
 */
export const LANGUAGES_LIST: LanguageDefinition[] = [
  { code: "adi", name: "Adi", nativeName: "Adi", speechCode: "en-IN" },
  { code: "njm", name: "Angami", nativeName: "Tenyidie", speechCode: "en-IN" },
  { code: "apt", name: "Apatani", nativeName: "Tani / Apatani", speechCode: "en-IN" },
  { code: "as", name: "Assamese", nativeName: "অসমীয়া", speechCode: "as-IN" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", speechCode: "bn-IN" },
  { code: "djo", name: "Bhutia", nativeName: "འབྲས་ལྗོངས་སྐད་", speechCode: "en-IN" },
  { code: "brx", name: "Bodo", nativeName: "बड़ो", speechCode: "hi-IN" },
  { code: "ccp", name: "Chakma", nativeName: "চাকমা", speechCode: "bn-IN" },
  { code: "der", name: "Deori", nativeName: "দেউৰী", speechCode: "as-IN" },
  { code: "dis", name: "Dimasa", nativeName: "Grao-Dima", speechCode: "as-IN" },
  { code: "en", name: "English", nativeName: "English", speechCode: "en-US" },
  { code: "grt", name: "Garo", nativeName: "A·chik", speechCode: "en-IN" },
  { code: "gvr", name: "Gurung", nativeName: "तमु क्यी", speechCode: "ne-NP" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", speechCode: "hi-IN" },
  { code: "hmr", name: "Hmar", nativeName: "Hmar ṭawng", speechCode: "en-IN" },
  { code: "mjw", name: "Karbi", nativeName: "Karbi", speechCode: "as-IN" },
  { code: "kht", name: "Khamti", nativeName: "ၵႂၢမ်းၶမ်းတီႈ", speechCode: "en-IN" },
  { code: "kha", name: "Khasi", nativeName: "Ka Ktien Khasi", speechCode: "en-IN" },
  { code: "trp", name: "Kokborok", nativeName: "Kokborok", speechCode: "bn-IN" },
  { code: "opm", name: "Konyak", nativeName: "Konyak", speechCode: "en-IN" },
  { code: "cnh", name: "Lai", nativeName: "Lai holh", speechCode: "en-IN" },
  { code: "lep", name: "Lepcha", nativeName: "ᰛᰩᰵᰛᰧᰵ", speechCode: "en-IN" },
  { code: "lif", name: "Limbu", nativeName: "ᤕᤠᤰᤌᤢᤱ ᤐᤠᤴ", speechCode: "ne-NP" },
  { code: "lot", name: "Lotha", nativeName: "Lotha", speechCode: "en-IN" },
  { code: "nbi", name: "Mao", nativeName: "Mao / Emela", speechCode: "en-IN" },
  { code: "mni", name: "Meiteilon (Manipuri)", nativeName: "ꯃꯤꯇꯩꯂꯣꯟ", speechCode: "hi-IN" },
  { code: "mrg", name: "Mishing", nativeName: "Mising agom", speechCode: "as-IN" },
  { code: "lus", name: "Mizo", nativeName: "Mizo ṭawng", speechCode: "en-IN" },
  { code: "mda", name: "Monpa", nativeName: "མོན་པ", speechCode: "en-IN" },
  { code: "nag", name: "Nagamese", nativeName: "Nagamese", speechCode: "as-IN" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली", speechCode: "ne-NP" },
  { code: "njb", name: "Nocte", nativeName: "Nocte", speechCode: "en-IN" },
  { code: "njz", name: "Nyishi", nativeName: "Nyishi", speechCode: "en-IN" },
  { code: "pck", name: "Paite", nativeName: "Paite pau", speechCode: "en-IN" },
  { code: "pbv", name: "Pnar (Jaintia)", nativeName: "Pnar", speechCode: "en-IN" },
  { code: "rah", name: "Rabha", nativeName: "ৰাভা", speechCode: "as-IN" },
  { code: "rab", name: "Rai", nativeName: "राई", speechCode: "ne-NP" },
  { code: "rnp", name: "Rongmei", nativeName: "Rongmei", speechCode: "en-IN" },
  { code: "xsr", name: "Sherpa", nativeName: "ཤར་པའི་སྐད་", speechCode: "ne-NP" },
  { code: "sip", name: "Sikkimese", nativeName: "འབྲས་ལྗོངས་སྐད་", speechCode: "en-IN" },
  { code: "nsm", name: "Sumi", nativeName: "Sumi", speechCode: "en-IN" },
  { code: "taj", name: "Tamang", nativeName: "तामाङ", speechCode: "ne-NP" },
  { code: "nmf", name: "Tangkhul", nativeName: "Tangkhul", speechCode: "en-IN" },
  { code: "nst", name: "Tangsa", nativeName: "Tangsa", speechCode: "en-IN" },
  { code: "lax", name: "Tiwa", nativeName: "তিৱা", speechCode: "as-IN" },
  { code: "nnp", name: "Wancho", nativeName: "Wancho", speechCode: "en-IN" },
];

/**
 * Common UI Translations Dictionary
 */
export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    appName: "NeuroSathi",
    tagline: "Cognitive Care & Companion",
    home: "Home",
    games: "Games",
    gamesCount: "Games (14)",
    aiChat: "AI Chat",
    aiVoice: "AI Voice",
    doctorPortal: "Doctor Portal",
    doctorConnect: "Doctor Connect",
    report: "Report",
    profile: "Profile",
    sos: "Emergency SOS",
    activeUser: "Active User",
    switchAccount: "Switch / Sign In (Doctor or Patient)",
    doctor: "Doctor",
    patient: "Patient",
    signOut: "Sign Out",
    searchLanguage: "Search language...",
    noLanguageFound: "No language found",

    // Home
    personalizedCompanion: "Personalized Companion",
    goodDay: "Good day",
    mindPrecious: "Your mind is precious. Take a few calm moments today to exercise your memory and connect with your care team.",
    startDailyWorkout: "Start Daily Brain Workout",
    voiceCompanion: "Voice Companion",
    cognitiveScore: "Cognitive Wellness Score",
    daysStreak: "Days Active Streak",
    quickBrainWorkout: "Quick Brain Workout",
    quickBrainWorkoutDesc: "Play short cognitive games scientifically tuned to stimulate memory and reflexes.",
    aiConsultation: "AI Health Consultation",
    aiConsultationDesc: "Chat or speak freely with NeuroSathi to assess mood, recount memories, or ask questions.",
    doctorConnection: "Doctor Connection",
    doctorConnectedDesc: "Connected directly with your attending physician for continuous review.",
    emergencyAlert: "Emergency SOS",
    emergencySubtitle: "Immediate distress alert sent to your physician and emergency care team.",
    dailyReminders: "Daily Reminders & Medications",
    addReminder: "Add Reminder",
    newReminderTitle: "Reminder description (e.g. Blood Pressure Pill)",
    saveReminder: "Save Reminder",
    cancel: "Cancel",
    noRemindersYet: "No reminders scheduled for today. Great job keeping your schedule clear!",
    completed: "Completed",
    pending: "Pending",

    // Games View
    cognitiveGym: "COGNITIVE STIMULATION GYM",
    brainFitnessGames: "14 Interactive Brain Fitness Games",
    gamesHeroDesc: "Evidence-based exercises designed to activate working memory, spatial reasoning, visual attention, and verbal recall.",
    allCategories: "All Categories",
    memory: "Memory",
    attention: "Attention",
    problemSolving: "Problem Solving",
    languageCat: "Language",
    motorSpeed: "Motor & Speed",
    difficulty: "Difficulty",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    playGame: "Play Game",
    score: "Score",
    mistakes: "Mistakes",
    accuracy: "Accuracy",
    timeSpent: "Time Spent",
    wellDone: "Well Done!",
    playAgain: "Play Again",
    nextLevel: "Next Level",
    backToGames: "Back to Games",

    // Doctor View
    doctorPortalTitle: "Doctor Clinical Portal",
    doctorPortalSubtitle: "Monitor patient cognitive progress, review game history, and provide direct consultations.",
    patientPortalTitle: "Doctor Connect",
    patientPortalSubtitle: "Communicate in real-time with your designated doctor and review clinical notes.",
    connectedPatients: "Connected Patients",
    noPatientsYet: "No patients connected to your Doctor ID yet.",
    shareDoctorId: "Share this ID with your patients to establish connection",
    myDoctorId: "My Unique Doctor ID",
    connectWithDoctor: "Connect with Doctor",
    enterDoctorId: "Enter Doctor ID (e.g. NS-DOC-7K4P92)",
    connectNow: "Connect Now",
    connectedDoctor: "Connected Doctor",
    typeMessage: "Type a message or question...",
    send: "Send",
    cognitiveHistory: "Cognitive Activity History",
    online: "Online",
    offline: "Offline",

    // Progress View
    reportTitle: "Health & Brain Report",
    reportSubtitle: "Detailed tracking of brain stimulation, working memory retention, and mental sharpness over time.",
    overallScore: "Overall Score",
    gamesPlayed: "Games Completed",
    retentionAccuracy: "Retention Accuracy",
    activeStreak: "Active Streak",
    printPdf: "Print / Export PDF",
    domainAverages: "Cognitive Domain Averages",

    // Profile
    profileSettings: "Profile & Health Settings",
    profileSettingsSubtitle: "Manage your health profile, emergency contacts, doctor code, and system preferences.",
    fullName: "Full Name",
    mobileNumber: "Mobile Number",
    email: "Email Address",
    preferredLanguage: "Preferred Language",
    emergencyContact: "Emergency Contact Name",
    emergencyPhone: "Emergency Contact Phone",
    medicalNotes: "Medical / Health Notes",
    saveChanges: "Save Profile Changes",

    // SOS
    emergencySosTitle: "EMERGENCY SOS",
    emergencySosSubtitle: "Pressing the button below immediately sends an emergency distress signal to your connected doctor.",
    tapToAlert: "Tap to Alert",
    alertSentTitle: "Alert Sent to Doctor!",
    alertSentSubtitle: "Your distress signal has been securely logged and dispatched to your physician.",
    emergencyHotlines: "Emergency Hotlines",

    // Auth
    welcomeToNeuroSathi: "Welcome to NeuroSathi",
    authSubtitle: "Log in or create an account to track your cognitive wellness and connect with your doctor.",
    signIn: "Sign In",
    signUp: "Create Account",
    phoneOtp: "Mobile Phone (OTP)",
    emailPassword: "Email & Password",
    enterMobile: "Enter 10-digit mobile number",
    sendCode: "Send Verification Code",
    enterOtp: "Enter 6-digit verification code",
    verifyComplete: "Verify Code & Complete",
    passwordLabel: "Password",
    specialization: "Specialization",
    hospitalOrClinic: "Hospital or Clinic",
  },

  hi: {
    appName: "न्यूरोसाथी",
    tagline: "मानसिक देखभाल और स्वास्थ्य साथी",
    home: "होम",
    games: "मस्तिष्क खेल",
    gamesCount: "खेल (14)",
    aiChat: "एआई चैट",
    aiVoice: "एआई आवाज़",
    doctorPortal: "डॉक्टर पोर्टल",
    doctorConnect: "डॉक्टर परामर्श",
    report: "प्रगति रिपोर्ट",
    profile: "प्रोफ़ाइल",
    sos: "आपातकालीन SOS",
    activeUser: "सक्रिय उपयोगकर्ता",
    switchAccount: "खाता बदलें / लॉगिन करें",
    doctor: "डॉक्टर",
    patient: "मरीज / वृद्धजन",
    signOut: "साइन आउट",
    searchLanguage: "भाषा खोजें...",
    noLanguageFound: "कोई भाषा नहीं मिली",

    // Home
    personalizedCompanion: "व्यक्तिगत स्वास्थ्य साथी",
    goodDay: "नमस्ते",
    mindPrecious: "आपका मस्तिष्क अनमोल है। अपनी याददाश्त को तरोताज़ा रखने और डॉक्टर से जुड़े रहने के लिए कुछ समय निकालें।",
    startDailyWorkout: "दैनिक दिमागी अभ्यास शुरू करें",
    voiceCompanion: "आवाज़ साथी",
    cognitiveScore: "मानसिक स्वास्थ्य स्कोर",
    daysStreak: "दिनों का सक्रिय क्रम",
    quickBrainWorkout: "त्वरित दिमागी खेल",
    quickBrainWorkoutDesc: "याददाश्त और फुर्ती बढ़ाने के लिए वैज्ञानिक रूप से तैयार खेल खेलें।",
    aiConsultation: "एआई स्वास्थ्य संवाद",
    aiConsultationDesc: "अपने मन की बात कहें, यादें साझा करें या प्रश्न पूछें।",
    doctorConnection: "डॉक्टर से जुड़ाव",
    doctorConnectedDesc: "निरंतर देखभाल के लिए अपने चिकित्सक से सीधे जुड़े रहें।",
    emergencyAlert: "आपातकालीन SOS",
    emergencySubtitle: "इसे दबाते ही आपके डॉक्टर और सहायता केंद्र को तुरंत संदेश भेजा जाएगा।",
    dailyReminders: "दैनिक दवाइयाँ और स्मरण",
    addReminder: "नया रिमाइंडर जोड़ें",
    newReminderTitle: "रिमाइंडर विवरण (उदा. रक्तचाप की दवा)",
    saveReminder: "सुरक्षित करें",
    cancel: "रद्द करें",
    noRemindersYet: "आज के लिए कोई अधूरा रिमाइंडर नहीं है। बहुत बढ़िया!",
    completed: "पूर्ण",
    pending: "बाकी",

    // Games View
    cognitiveGym: "मानसिक स्वास्थ्य जिम",
    brainFitnessGames: "14 दिमाग तेज करने वाले खेल",
    gamesHeroDesc: "कार्यशील स्मृति, स्थानिक सोच, एकाग्रता और शब्द स्मरण को सक्रिय करने के अभ्यास।",
    allCategories: "सभी श्रेणियाँ",
    memory: "स्मृति (याददाश्त)",
    attention: "एकाग्रता",
    problemSolving: "समस्या समाधान",
    languageCat: "भाषा",
    motorSpeed: "गति और सजगता",
    difficulty: "कठिनाई",
    easy: "सरल",
    medium: "मध्यम",
    hard: "कठिन",
    playGame: "खेलें",
    score: "अंक",
    mistakes: "गलतियाँ",
    accuracy: "सटीकता",
    timeSpent: "समय",
    wellDone: "शाबाश! बहुत बढ़िया!",
    playAgain: "फिर से खेलें",
    nextLevel: "अगला स्तर",
    backToGames: "खेल सूची पर लौटें",

    // Doctor View
    doctorPortalTitle: "डॉक्टर क्लिनिकल पोर्टल",
    doctorPortalSubtitle: "मरीजों की मानसिक प्रगति और खेल इतिहास की समीक्षा करें।",
    patientPortalTitle: "डॉक्टर परामर्श",
    patientPortalSubtitle: "अपने चिकित्सक से सीधा सुरक्षित संवाद करें।",
    connectedPatients: "जुड़े हुए मरीज",
    noPatientsYet: "अभी आपके डॉक्टर कोड से कोई मरीज नहीं जुड़ा है।",
    shareDoctorId: "मरीजों से जुड़ने के लिए यह ID साझा करें",
    myDoctorId: "मेरी डॉक्टर ID",
    connectWithDoctor: "डॉक्टर कोड से जुड़ें",
    enterDoctorId: "डॉक्टर ID दर्ज करें (उदा. NS-DOC-7K4P92)",
    connectNow: "अभी जुड़ें",
    connectedDoctor: "जुड़े हुए डॉक्टर",
    typeMessage: "संदेश या प्रश्न लिखें...",
    send: "भेजें",
    cognitiveHistory: "मानसिक गतिविधि इतिहास",
    online: "ऑनलाइन",
    offline: "ऑफ़लाइन",

    // Progress View
    reportTitle: "स्वास्थ्य एवं मस्तिष्क रिपोर्ट",
    reportSubtitle: "याददाश्त स्कोर, सजगता और मानसिक फिटनेस का विस्तृत विवरण।",
    overallScore: "कुल स्कोर",
    gamesPlayed: "खेले गए खेल",
    retentionAccuracy: "सटीकता दर",
    activeStreak: "सक्रिय क्रम",
    printPdf: "प्रिंट / PDF डाउनलोड",
    domainAverages: "डोमेन प्रदर्शन औसत",

    // Profile
    profileSettings: "प्रोफ़ाइल एवं सेटिंग्स",
    profileSettingsSubtitle: "व्यक्तिगत जानकारी, डॉक्टर कोड और आपातकालीन संपर्क प्रबंधित करें।",
    fullName: "पूरा नाम",
    mobileNumber: "मोबाइल नंबर",
    email: "ईमेल पता",
    preferredLanguage: "पसंदीदा भाषा",
    emergencyContact: "आपातकालीन संपर्क का नाम",
    emergencyPhone: "आपातकालीन संपर्क फोन",
    medicalNotes: "स्वास्थ्य विवरण व दवाइयाँ",
    saveChanges: "बदलाव सहेजें",

    // SOS
    emergencySosTitle: "आपातकालीन SOS",
    emergencySosSubtitle: "यह बटन दबाते ही आपके डॉक्टर को आपात संदेश भेजा जाएगा।",
    tapToAlert: "आपात सूचना भेजें",
    alertSentTitle: "डॉक्टर को सूचना भेजी गई!",
    alertSentSubtitle: "आपकी आपात सूचना सुरक्षित रूप से दर्ज कर डॉक्टर को भेज दी गई है।",
    emergencyHotlines: "आपातकालीन हेल्पलाइन",

    // Auth
    welcomeToNeuroSathi: "न्यूरोसाथी में आपका स्वागत है",
    authSubtitle: "अपनी याददाश्त की देखभाल और डॉक्टर से जुड़ने के लिए लॉगिन करें।",
    signIn: "लॉगिन करें",
    signUp: "नया खाता बनाएँ",
    phoneOtp: "मोबाइल नंबर (OTP)",
    emailPassword: "ईमेल व पासवर्ड",
    enterMobile: "10-अंकों का मोबाइल नंबर दर्ज करें",
    sendCode: "OTP कोड भेजें",
    enterOtp: "6-अंकों का कोड दर्ज करें",
    verifyComplete: "सत्यापित करें",
    passwordLabel: "पासवर्ड",
    specialization: "विशेषज्ञता",
    hospitalOrClinic: "अस्पताल या क्लिनिक",
  },

  as: {
    appName: "নিউৰোসাথী",
    tagline: "আপোনাৰ মৰমৰ মানসিক সংগী আৰু স্বাস্থ্য ৰক্ষক",
    home: "গৃহ",
    games: "মস্তিষ্কৰ খেল",
    gamesCount: "খেল (১৪)",
    aiChat: "এআই চেট",
    aiVoice: "এআই কণ্ঠ",
    doctorPortal: "চিকিৎসক পৰ্টেল",
    doctorConnect: "চিকিৎসক সংযোগ",
    report: "প্ৰতিবেদন",
    profile: "প্ৰফাইল",
    sos: "জৰুৰীকালীন SOS",
    activeUser: "সক্ৰিয় ব্যৱহাৰকাৰী",
    switchAccount: "একাউণ্ট সলনি কৰক / লগইন",
    doctor: "চিকিৎসক",
    patient: "ৰোগী / জ্যেষ্ঠজন",
    signOut: "লগ আউট",
    searchLanguage: "ভাষা সন্ধান কৰক...",
    noLanguageFound: "কোনো ভাষা পোৱা নগ'ল",

    personalizedCompanion: "ব্যক্তিগত স্বাস্থ্য সংগী",
    goodDay: "নমস্কাৰ",
    mindPrecious: "আপোনাৰ মন অতি মূল্যবান। স্মৃতিশক্তি বৃদ্ধি আৰু স্বাস্থ্যৰ বাবে প্ৰতিদিনে অলপ সময় খেলক।",
    startDailyWorkout: "দৈনিক মগজুৰ অনুশীলন আৰম্ভ কৰক",
    voiceCompanion: "কণ্ঠ সংগী",
    cognitiveScore: "মানসিক সুস্থতা নম্বৰ",
    daysStreak: "দিন ধৰি সক্ৰিয়",
    quickBrainWorkout: "ক্ষিপ্ৰ মগজুৰ খেল",
    quickBrainWorkoutDesc: "স্মৃতিশক্তি আৰু মনোযোগ বৃদ্ধিৰ বাবে বৈজ্ঞানিক খেল খেলক।",
    aiConsultation: "এআই স্বাস্থ্য পৰামৰ্শ",
    aiConsultationDesc: "নিউৰোসাথীৰ লগত মনৰ কথা পাতক, প্ৰশ্ন সোধক।",
    doctorConnection: "চিকিৎসকৰ সৈতে সংযোগ",
    doctorConnectedDesc: "আপোনাৰ চিকিৎসকৰ সৈতে সদায় সংযুক্ত থাকক।",
    emergencyAlert: "জৰুৰীকালীন SOS",
    emergencySubtitle: "ই স্পর্শ কৰাৰ লগে লগে আপোনাৰ চিকিৎসকক জৰুৰী বাৰ্তা প্ৰেৰণ কৰা হ'ব।",
    dailyReminders: "দৈনিক সোঁৱৰণী আৰু ঔষধ",
    addReminder: "নতুন সোঁৱৰণী যোগ কৰক",
    newReminderTitle: "সোঁৱৰণীৰ বিৱৰণ (যেনে: ৰক্তচাপৰ ঔষধ)",
    saveReminder: "সংৰক্ষণ কৰক",
    cancel: "বাতিল",
    noRemindersYet: "আজিৰ বাবে কোনো বাকী থকা সোঁৱৰণী নাই।",
    completed: "সম্পূৰ্ণ",
    pending: "বাকী",

    cognitiveGym: "মানসিক স্বাস্থ্য ব্যায়ামাগাৰ",
    brainFitnessGames: "১৪ টা মগজু সবল কৰা খেল",
    gamesHeroDesc: "কাৰ্যকৰী স্মৃতি, স্থানিক চিন্তা আৰু মনোযোগ বৃদ্ধিৰ বাবে বিশেষ খেল।",
    allCategories: "সকলো ভাগ",
    memory: "স্মৃতিশক্তি",
    attention: "মনোযোগ",
    problemSolving: "সমস্যা সমাধান",
    languageCat: "ভাষা",
    motorSpeed: "গতি আৰু ক্ষিপ্ৰতা",
    difficulty: "কঠিনতা",
    easy: "সহজ",
    medium: "মধ্যম",
    hard: "কঠিন",
    playGame: "খেল আৰম্ভ কৰক",
    score: "নম্বৰ",
    mistakes: "ভুল",
    accuracy: "শুদ্ধতা",
    timeSpent: "সময়",
    wellDone: "বহুত ভাল হ'ল!",
    playAgain: "পুনৰ খেলক",
    nextLevel: "পৰৱৰ্তী স্তৰ",
    backToGames: "খেলৰ তালিকালৈ উভতি যাওক",

    doctorPortalTitle: "চিকিৎসক পৰ্টেল",
    doctorPortalSubtitle: "ৰোগীৰ স্মৃতিশক্তি উন্নতি আৰু খেলৰ খতিয়ান নিৰীক্ষণ কৰক।",
    patientPortalTitle: "চিকিৎসক সংযোগ",
    patientPortalSubtitle: "চিকিৎসকৰ সৈতে সঁচা সময়ত কথা পাতক।",
    connectedPatients: "সংযুক্ত ৰোগীসকল",
    noPatientsYet: "এতিয়ালৈ কোনো ৰোগী সংযুক্ত হোৱা নাই।",
    shareDoctorId: "ৰোগীৰ সৈতে এই ID শ্বেয়াৰ কৰক",
    myDoctorId: "মোৰ চিকিৎসক ID",
    connectWithDoctor: "চিকিৎসক ID ৰে সংযোগ কৰক",
    enterDoctorId: "চিকিৎসক ID লিখক",
    connectNow: "এতিয়াই সংযোগ কৰক",
    connectedDoctor: "সংযুক্ত চিকিৎসক",
    typeMessage: "বাৰ্তা বা প্ৰশ্ন লিখক...",
    send: "প্ৰেৰণ",
    cognitiveHistory: "মানসিক খেলৰ ইতিহাস",
    online: "অনলাইন",
    offline: "অফলাইন",

    reportTitle: "স্বাস্থ্য আৰু স্মৃতি প্ৰতিবেদন",
    reportSubtitle: "মগজুৰ উদ্দীপনা আৰু স্মৃতিশক্তিৰ অগ্ৰগতিৰ বিতং তথ্য।",
    overallScore: "সামগ্ৰিক নম্বৰ",
    gamesPlayed: "সম্পূৰ্ণ কৰা খেল",
    retentionAccuracy: "শুদ্ধতাৰ হাৰ",
    activeStreak: "সক্ৰিয় দিন",
    printPdf: "প্ৰিণ্ট / PDF সংগ্ৰহ",
    domainAverages: "শাখাভিত্তিক প্ৰদৰ্শন",

    profileSettings: "প্ৰফাইল আৰু স্বাস্থ্য ছেটিংছ",
    profileSettingsSubtitle: "আপোনাৰ স্বাস্থ্য বিৱৰণ আৰু জৰুৰী যোগাযোগ তথ্য পৰিচালনা কৰক।",
    fullName: "সম্পূৰ্ণ নাম",
    mobileNumber: "মোবাইল নম্বৰ",
    email: "ইমেইল ঠিকনা",
    preferredLanguage: "পছন্দৰ ভাষা",
    emergencyContact: "জৰুৰীকালীন যোগাযোগৰ নাম",
    emergencyPhone: "জৰুৰীকালীন ফোন",
    medicalNotes: "স্বাস্থ্য টোকা আৰু ঔষধ",
    saveChanges: "পৰিৱৰ্তন সংৰক্ষণ কৰক",

    emergencySosTitle: "জৰুৰীকালীন SOS",
    emergencySosSubtitle: "তলৰ বুটামটো টিপিলে আপোনাৰ চিকিৎসকক সতৰ্কবাৰ্তা প্ৰেৰণ হ'ব।",
    tapToAlert: "সতৰ্কবাৰ্তা প্ৰেৰণ কৰক",
    alertSentTitle: "চিকিৎসকক বাৰ্তা প্ৰেৰণ কৰা হ'ল!",
    alertSentSubtitle: "আপোনাৰ সংকেত সংৰক্ষণ হৈ চিকিৎসকৰ ওচৰলৈ গ'ল।",
    emergencyHotlines: "জৰুৰীকালীন হেল্পলাইন",

    welcomeToNeuroSathi: "নিউৰোসাথীলৈ স্বাগতম",
    authSubtitle: "আপোনাৰ মানসিক স্বাস্থ্য পৰীক্ষা আৰু চিকিৎসকৰ সৈতে সংযোগ কৰিবলৈ লগইন কৰক।",
    signIn: "লগইন",
    signUp: "নতুন একাউণ্ট",
    phoneOtp: "মোবাইল নম্বৰ (OTP)",
    emailPassword: "ইমেইল আৰু পাছৱৰ্ড",
    enterMobile: "১০ সংখ্যাৰ মোবাইল নম্বৰ লিখক",
    sendCode: "OTP প্ৰেৰণ কৰক",
    enterOtp: "৬ সংখ্যাৰ কোড লিখক",
    verifyComplete: "প্ৰমাণিত কৰক",
    passwordLabel: "পাছৱৰ্ড",
    specialization: "বিশেষজ্ঞতা",
    hospitalOrClinic: "চিকিৎসালয় বা ক্লিনিক",
  },

  bn: {
    appName: "নিউরোসাথী",
    tagline: "আপনার স্নেহের মানসিক সঙ্গী ও স্বাস্থ্য রক্ষক",
    home: "হোম",
    games: "মস্তিষ্কের খেলা",
    gamesCount: "খেলা (১৪)",
    aiChat: "এআই চ্যাট",
    aiVoice: "এআই কণ্ঠস্বর",
    doctorPortal: "ডাক্তার পোর্টাল",
    doctorConnect: "ডাক্তারের সাথে যোগাযোগ",
    report: "অগ্রগতি রিপোর্ট",
    profile: "প্রোফাইল",
    sos: "জরুরি SOS",
    activeUser: "সক্রিয় ব্যবহারকারী",
    switchAccount: "অ্যাকাউন্ট পরিবর্তন / লগইন",
    doctor: "ডাক্তার",
    patient: "রোগী / প্রবীণ",
    signOut: "লগ আউট",
    searchLanguage: "ভাষা খুঁজুন...",
    noLanguageFound: "কোনো ভাষা পাওয়া যায়নি",

    personalizedCompanion: "ব্যক্তিগত স্বাস্থ্য সঙ্গী",
    goodDay: "নমস্কার",
    mindPrecious: "আপনার মন অত্যন্ত মূল্যবান। স্মৃতিশক্তি সতেজ রাখতে প্রতিদিন একটু সময় দিন।",
    startDailyWorkout: "দৈনিক মস্তিষ্কের ব্যায়াম শুরু করুন",
    voiceCompanion: "ভয়েস সঙ্গী",
    cognitiveScore: "মানসিক সুস্থতা স্কোর",
    daysStreak: "দিনের সক্রিয় ধারাবাহিকতা",
    quickBrainWorkout: "দ্রুত মস্তিষ্কের খেলা",
    quickBrainWorkoutDesc: "স্মৃতিশক্তি ও একাগ্রতা বাড়াতে বৈজ্ঞানিক খেলা খেলুন।",
    aiConsultation: "এআই স্বাস্থ্য পরামর্শ",
    aiConsultationDesc: "নিউরোসাথীর সাথে মন খুলে কথা বলুন বা প্রশ্ন করুন।",
    doctorConnection: "ডাক্তারের সাথে সংযোগ",
    doctorConnectedDesc: "আপনার চিকিৎসকের সাথে সর্বদা সংযুক্ত থাকুন।",
    emergencyAlert: "জরুরি SOS",
    emergencySubtitle: "এটি চাপার সাথে সাথে আপনার ডাক্তার ও জরুরি বিভাগে বার্তা চলে যাবে।",
    dailyReminders: "দৈনিক ওষুধ ও রুটিন",
    addReminder: "নতুন রিমাইন্ডার যোগ করুন",
    newReminderTitle: "রিমাইন্ডারের বিবরণ (যেমন: রক্তচাপের ওষুধ)",
    saveReminder: "সংরক্ষণ করুন",
    cancel: "বাতিল",
    noRemindersYet: "আজকের জন্য কোনো বাকি রিমাইন্ডার নেই। দারুণ!",
    completed: "সম্পন্ন",
    pending: "বাকি",

    cognitiveGym: "মানসিক স্বাস্থ্যের জিম",
    brainFitnessGames: "১৪টি মস্তিষ্ক সতেজকারী খেলা",
    gamesHeroDesc: "স্মৃতিশক্তি, একাগ্রতা ও চিন্তা করার ক্ষমতা বৃদ্ধির বিশেষ খেলা।",
    allCategories: "সকল বিভাগ",
    memory: "স্মৃতিশক্তি",
    attention: "মনোযোগ",
    problemSolving: "সমস্যা সমাধান",
    languageCat: "ভাষা",
    motorSpeed: "গতি ও সতর্কতা",
    difficulty: "কঠিনতা",
    easy: "সহজ",
    medium: "মাঝারি",
    hard: "কঠিন",
    playGame: "খেলা শুরু করুন",
    score: "স্কোর",
    mistakes: "ভুল",
    accuracy: "সঠিকতা",
    timeSpent: "সময়",
    wellDone: "খুব ভালো হয়েছে!",
    playAgain: "আবার খেলুন",
    nextLevel: "পরবর্তী লেভেল",
    backToGames: "খেলার তালিকায় ফিরুন",

    doctorPortalTitle: "ডাক্তার ক্লিনিক্যাল পোর্টাল",
    doctorPortalSubtitle: "রোগীর স্মৃতিশক্তি উন্নতি ও খেলার ইতিহাস পর্যবেক্ষণ করুন।",
    patientPortalTitle: "ডাক্তার সংযোগ",
    patientPortalSubtitle: "ডাক্তারের সাথে সরাসরি কথা বলুন।",
    connectedPatients: "সংযুক্ত রোগীগণ",
    noPatientsYet: "এখনও কোনো রোগী সংযুক্ত হয়নি।",
    shareDoctorId: "রোগীর সাথে এই ID শেয়ার করুন",
    myDoctorId: "আমার ডাক্তার ID",
    connectWithDoctor: "ডাক্তার ID দিয়ে সংযোগ করুন",
    enterDoctorId: "ডাক্তার ID লিখুন",
    connectNow: "এখনই সংযোগ করুন",
    connectedDoctor: "সংযুক্ত ডাক্তার",
    typeMessage: "বার্তা বা প্রশ্ন লিখুন...",
    send: "পাঠান",
    cognitiveHistory: "মানসিক খেলার ইতিহাস",
    online: "অনলাইন",
    offline: "অফলাইন",

    reportTitle: "স্বাস্থ্য ও মস্তিষ্ক রিপোর্ট",
    reportSubtitle: "স্মৃতিশক্তি ও মানসিক সুস্থতার বিস্তারিত অগ্রগতি রিপোর্ট।",
    overallScore: "সামগ্রিক স্কোর",
    gamesPlayed: "সম্পন্ন খেলা",
    retentionAccuracy: "সঠিকতার হার",
    activeStreak: "সক্রিয় দিন",
    printPdf: "প্রিন্ট / PDF ডাউনলোড",
    domainAverages: "শাখাভিত্তিক গড়",

    profileSettings: "প্রোফাইল ও স্বাস্থ্য সেটিংস",
    profileSettingsSubtitle: "ব্যক্তিগত তথ্য, ডাক্তার কোড ও জরুরি যোগাযোগ পরিচালনা করুন।",
    fullName: "সম্পূর্ণ নাম",
    mobileNumber: "মোবাইল নম্বর",
    email: "ইমেইল ঠিকানা",
    preferredLanguage: "পছন্দের ভাষা",
    emergencyContact: "জরুরি যোগাযোগের নাম",
    emergencyPhone: "জরুরি ফোন নম্বর",
    medicalNotes: "স্বাস্থ্য নোট ও ওষুধ",
    saveChanges: "পরিবর্তন সংরক্ষণ করুন",

    emergencySosTitle: "জরুরি SOS",
    emergencySosSubtitle: "নিচের বোতামটি চাপলে ডাক্তারের কাছে জরুরি বার্তা পৌঁছে যাবে।",
    tapToAlert: "জরুরি বার্তা পাঠান",
    alertSentTitle: "ডাক্তারকে বার্তা পাঠানো হয়েছে!",
    alertSentSubtitle: "আপনার সংকেত সংরক্ষিত হয়ে চিকিৎসকের কাছে পৌঁছে গেছে।",
    emergencyHotlines: "জরুরি হটলাইন",

    welcomeToNeuroSathi: "নিউরোসাথীতে স্বাগতম",
    authSubtitle: "স্মৃতিশক্তি সুস্থ রাখা এবং ডাক্তারের সাথে যোগাযোগের জন্য লগইন করুন।",
    signIn: "লগইন",
    signUp: "নতুন অ্যাকাউন্ট",
    phoneOtp: "মোবাইল নম্বর (OTP)",
    emailPassword: "ইমেইল ও পাসওয়ার্ড",
    enterMobile: "১০ সংখ্যার মোবাইল নম্বর দিন",
    sendCode: "OTP পাঠান",
    enterOtp: "৬ সংখ্যার কোড লিখুন",
    verifyComplete: "যাচাই সম্পন্ন করুন",
    passwordLabel: "পাসওয়ার্ড",
    specialization: "বিশেষজ্ঞতা",
    hospitalOrClinic: "হাসপাতাল বা ক্লিনিক",
  },

  ne: {
    appName: "न्युरोसाथी",
    tagline: "तपाईंको मायालु मानसिक साथी र स्वास्थ्य रक्षक",
    home: "गृहपृष्ठ",
    games: "दिमागी खेलहरू",
    gamesCount: "खेलहरू (१४)",
    aiChat: "एआई कुराकानी",
    aiVoice: "एआई आवाज",
    doctorPortal: "डाक्टर पोर्टल",
    doctorConnect: "डाक्टर परामर्श",
    report: "प्रगति प्रतिवेदन",
    profile: "प्रोफाइल",
    sos: "आपतकालीन SOS",
    activeUser: "सक्रिय प्रयोगकर्ता",
    switchAccount: "खाता परिवर्तन / लगइन",
    doctor: "डाक्टर",
    patient: "बिरामी / ज्येष्ठ नागरिक",
    signOut: "साइन आउट",
    searchLanguage: "भाषा खोज्नुहोस्...",
    noLanguageFound: "कुनै भाषा भेटिएन",

    personalizedCompanion: "व्यक्तिगत स्वास्थ्य साथी",
    goodDay: "नमस्ते",
    mindPrecious: "तपाईंको मस्तिष्क अमूल्य छ। स्मरणशक्ति बलियो बनाउन दिनहुँ केही समय खेल्नुहोस्।",
    startDailyWorkout: "दैनिक दिमागी अभ्यास सुरु गर्नुहोस्",
    voiceCompanion: "आवाज साथी",
    cognitiveScore: "मानसिक स्वास्थ्य स्कोर",
    daysStreak: "दिन सक्रिय",
    quickBrainWorkout: "छिटो दिमागी खेल",
    quickBrainWorkoutDesc: "स्मरणशक्ति र ध्यान बढाउन वैज्ञानिक खेलहरू खेल्नुहोस्।",
    aiConsultation: "एआई स्वास्थ्य सल्लाह",
    aiConsultationDesc: "न्युरोसाथीसँग खुलेर कुरा गर्नुहोस् वा प्रश्न सोध्नुहोस्।",
    doctorConnection: "डाक्टरसँगको सम्बन्ध",
    doctorConnectedDesc: "आफ्नो चिकित्सकसँग निरन्तर सम्पर्कमा रहनुहोस्।",
    emergencyAlert: "आपतकालीन SOS",
    emergencySubtitle: "यो थिच्दा डाक्टर र आपतकालीन टोलीलाई तुरुन्त सन्देश जानेछ।",
    dailyReminders: "दैनिक औषधि र सम्झनाहरू",
    addReminder: "नयाँ सम्झना थप्नुहोस्",
    newReminderTitle: "औषधि वा तालिका (जस्तै: रक्तचापको औषधि)",
    saveReminder: "सुरक्षित गर्नुहोस्",
    cancel: "रद्द गर्नुहोस्",
    noRemindersYet: "आजका लागि कुनै बाँकी तालिका छैन। धेरै राम्रो!",
    completed: "सम्पन्न",
    pending: "बाँकी",

    cognitiveGym: "मानसिक स्वास्थ्य जिम",
    brainFitnessGames: "१४ दिमागी खेलहरू",
    gamesHeroDesc: "स्मरणशक्ति, ध्यान र तर्कशक्ति बढाउने वैज्ञानिक अभ्यासहरू।",
    allCategories: "सबै वर्गहरू",
    memory: "स्मरणशक्ति",
    attention: "एकाग्रता",
    problemSolving: "समस्या समाधान",
    languageCat: "भाषा",
    motorSpeed: "गति र सजगता",
    difficulty: "कठिनाई",
    easy: "सजिलो",
    medium: "मध्यम",
    hard: "गाह्रो",
    playGame: "खेल सुरु गर्नुहोस्",
    score: "अङ्क",
    mistakes: "गल्तीहरू",
    accuracy: "सटीकता",
    timeSpent: "समय",
    wellDone: "धेरै राम्रो!",
    playAgain: "फेरि खेल्नुहोस्",
    nextLevel: "अर्को स्तर",
    backToGames: "खेल सूचीमा फर्कनुहोस्",

    doctorPortalTitle: "डाक्टर क्लिनिकल पोर्टल",
    doctorPortalSubtitle: "बिरामीको मानसिक प्रगति र खेल इतिहास हेर्नुहोस्।",
    patientPortalTitle: "डाक्टर परामर्श",
    patientPortalSubtitle: "आफ्नो डाक्टरसँग सिधै कुरा गर्नुहोस्।",
    connectedPatients: "जोडिएका बिरामीहरू",
    noPatientsYet: "अहिलेसम्म कुनै बिरामी जोडिएका छैनन्।",
    shareDoctorId: "बिरामीसँग यो ID साझा गर्नुहोस्",
    myDoctorId: "मेरो डाक्टर ID",
    connectWithDoctor: "डाक्टर ID बाट जोडिनुहोस्",
    enterDoctorId: "डाक्टर ID प्रविष्ट गर्नुहोस्",
    connectNow: "अहिले जोड्नुहोस्",
    connectedDoctor: "जोडिनुभएको डाक्टर",
    typeMessage: "सन्देश वा प्रश्न लेख्नुहोस्...",
    send: "पठाउनुहोस्",
    cognitiveHistory: "मानसिक खेल इतिहास",
    online: "अनलाइन",
    offline: "अफलाइन",

    reportTitle: "स्वास्थ्य र मस्तिष्क प्रतिवेदन",
    reportSubtitle: "स्मरणशक्ति र मानसिक स्वास्थ्य सुधारको विस्तृत विवरण।",
    overallScore: "कुल अङ्क",
    gamesPlayed: "सम्पन्न खेलहरू",
    retentionAccuracy: "सटीकता दर",
    activeStreak: "सक्रिय दिनहरू",
    printPdf: "प्रिन्ट / PDF डाउनलोड",
    domainAverages: "क्षेत्रगत औसत",

    profileSettings: "प्रोफाइल र स्वास्थ्य सेटिङहरू",
    profileSettingsSubtitle: "व्यक्तिगत विवरण, डाक्टर कोड र आपतकालीन सम्पर्क व्यवस्थापन गर्नुहोस्।",
    fullName: "पूरा नाम",
    mobileNumber: "मोबाइल नम्बर",
    email: "इमेल ठेगाना",
    preferredLanguage: "रोजेको भाषा",
    emergencyContact: "आपतकालीन सम्पर्कको नाम",
    emergencyPhone: "आपतकालीन फोन",
    medicalNotes: "स्वास्थ्य टिपोट र औषधिहरू",
    saveChanges: "परिवर्तन सुरक्षित गर्नुहोस्",

    emergencySosTitle: "आपतकालीन SOS",
    emergencySosSubtitle: "तलको बटन थिच्दा डाक्टरलाई तुरुन्त आपतकालीन सन्देश जानेछ।",
    tapToAlert: "आपतकालीन सूचना पठाउनुहोस्",
    alertSentTitle: "डाक्टरलाई सूचना पठाइयो!",
    alertSentSubtitle: "तपाईंको संकेत सुरक्षित रूपमा डाक्टरलाई पुगेको छ।",
    emergencyHotlines: "आपतकालीन हेल्पलाइन",

    welcomeToNeuroSathi: "न्युरोसाथीमा स्वागत छ",
    authSubtitle: "स्मरणशक्ति सुधार र डाक्टरसँग सम्पर्कका लागि लगइन गर्नुहोस्।",
    signIn: "लगइन",
    signUp: "नयाँ खाता",
    phoneOtp: "मोबाइल नम्बर (OTP)",
    emailPassword: "इमेल र पासवर्ड",
    enterMobile: "१० अङ्कको मोबाइल नम्बर हाल्नुहोस्",
    sendCode: "OTP पठाउनुहोस्",
    enterOtp: "६ अङ्कको कोड हाल्नुहोस्",
    verifyComplete: "प्रमाणीकरण गर्नुहोस्",
    passwordLabel: "पासवर्ड",
    specialization: "विशेषज्ञता",
    hospitalOrClinic: "अस्पताल वा क्लिनिक",
  },

  mni: {
    appName: "NeuroSathi",
    tagline: "ꯅꯈꯣꯏꯒꯤ ꯊꯋꯥꯏ ꯄꯨꯛꯅꯤꯡ ꯑꯃꯁꯨꯡ ꯍꯛꯁꯦꯜ ꯌꯦꯡꯁꯤꯅꯕ",
    home: "ꯌꯨꯝ (Home)",
    games: "ꯋꯥꯈꯜ ꯁꯥꯟꯅꯄꯣꯠ",
    gamesCount: "ꯁꯥꯟꯅꯄꯣꯠ (14)",
    aiChat: "AI ꯋꯥꯇꯥꯟꯅꯕ",
    aiVoice: "AI ꯈꯣꯟꯊꯣꯛ",
    doctorPortal: "ꯗꯣꯛꯇꯔ ꯄꯣꯔꯇꯦꯜ",
    doctorConnect: "ꯗꯣꯛꯇꯔ ꯎꯅꯕ",
    report: "ꯄ꯭ꯔꯣꯒ꯭ꯔꯦꯁ ꯔꯤꯄꯣꯔꯠ",
    profile: "ꯄ꯭ꯔꯣꯐꯥꯏꯜ",
    sos: "ꯑꯀꯅꯕ SOS",
    activeUser: "ꯁꯤꯖꯤꯟꯅꯔꯤꯕ",
    switchAccount: "ꯑꯦꯀꯥꯎꯟꯠ ꯁꯂꯥꯏꯕ",
    doctor: "ꯗꯣꯛꯇꯔ",
    patient: "ꯑꯅꯥꯕ / ꯑꯍꯜ",
    signOut: "ꯁꯥꯏꯟ ꯑꯥꯎꯠ",
    searchLanguage: "ꯂꯣꯟ ꯊꯤꯕ...",
    noLanguageFound: "ꯂꯣꯟ ꯐꯪꯗ꯭ꯔꯦ",

    personalizedCompanion: "ꯄꯨꯛꯅꯤꯡ ꯂꯩꯅꯕ ꯃꯔꯨꯞ",
    goodDay: "ꯈꯨꯔꯨꯝꯖꯔꯤ",
    mindPrecious: "ꯅꯍꯥꯛꯀꯤ ꯋꯥꯈꯜ ꯑꯁꯤ ꯌꯥꯝꯅ ꯃꯔꯨꯑꯣꯏ। ꯅꯤꯡꯁꯤꯡ ꯁꯛꯇꯤ ꯍꯦꯟꯒꯠꯅꯕ ꯅꯨꯃꯤꯠ ꯈꯨꯗꯤꯡꯒꯤ ꯁꯥꯟꯅꯕꯤꯌꯨ।",
    startDailyWorkout: "ꯅꯨꯃꯤꯠ ꯈꯨꯗꯤꯡꯒꯤ ꯋꯥꯈꯜ ꯁꯥꯟꯅꯕ",
    voiceCompanion: "ꯈꯣꯟꯊꯣꯛ ꯃꯔꯨꯞ",
    cognitiveScore: "ꯋꯥꯈꯜ ꯍꯛꯁꯦꯜ ꯁ꯭ꯀꯣꯔ",
    daysStreak: "ꯅꯨꯃꯤꯠ ꯂꯦꯞꯇꯅ ꯁꯥꯟꯅꯔꯤꯕ",
    quickBrainWorkout: "ꯊꯨꯅ ꯁꯥꯟꯅꯕ ꯃꯁꯥꯟꯅ",
    quickBrainWorkoutDesc: "ꯋꯥꯈꯜ ꯆꯦꯠꯁꯤꯜꯍꯟꯅꯕ ꯁꯥꯟꯅꯄꯣꯠꯁꯤꯡ।",
    aiConsultation: "AI ꯍꯛꯁꯦꯜ ꯄꯥꯎꯇꯥꯛ",
    aiConsultationDesc: "NeuroSathi ꯒ ꯋꯥ ꯇꯥꯟꯅꯕꯤꯌꯨ।",
    doctorConnection: "ꯗꯣꯛꯇꯔꯒ ꯁꯝꯅꯕ",
    doctorConnectedDesc: "ꯗꯣꯛꯇꯔꯒ ꯍꯛꯊꯦꯡꯅꯅ ꯁꯝꯅꯕꯤꯌꯨ।",
    emergencyAlert: "ꯑꯀꯅꯕ SOS",
    emergencySubtitle: "ꯃꯁꯤ ꯅꯝꯂꯒ ꯗꯣꯛꯇꯔꯗ ꯑꯀꯅꯕ ꯄꯥꯎ ꯌꯧꯒꯅꯤ।",
    dailyReminders: "ꯅꯨꯃꯤꯠ ꯈꯨꯗꯤꯡꯒꯤ ꯍꯤꯗꯥꯛ",
    addReminder: "ꯑꯅꯧꯕ ꯅꯤꯡꯁꯤꯡꯍꯟꯕ",
    newReminderTitle: "ꯍꯤꯗꯥꯛ ꯃꯃꯤꯡ",
    saveReminder: "ꯊꯝꯃꯨ",
    cancel: "ꯇꯣꯛꯂꯣ",
    noRemindersYet: "ꯉꯁꯤꯒꯤ ꯑꯣꯏꯅ ꯂꯩꯇꯦ।",
    completed: "ꯂꯣꯏꯔꯦ",
    pending: "ꯂꯩꯔꯤ",

    cognitiveGym: "ꯋꯥꯈꯜ ꯍꯛꯁꯦꯜ ꯁꯥꯟꯅꯐꯝ",
    brainFitnessGames: "ꯋꯥꯈꯜ ꯀꯪꯍꯟꯅꯕ ꯃꯁꯥꯟꯅ 14",
    gamesHeroDesc: "ꯅꯤꯡꯁꯤꯡ ꯁꯛꯇꯤ ꯑꯃꯁꯨꯡ ꯋꯥꯈꯜ ꯆꯦꯠꯍꯟꯅꯕ ꯁꯥꯟꯅꯄꯣꯠꯁꯤꯡ।",
    allCategories: "ꯄꯨꯝꯅꯃꯛ",
    memory: "ꯅꯤꯡꯁꯤꯡ ꯁꯛꯇꯤ",
    attention: "ꯃꯤꯠꯌꯦꯡ ꯊꯝꯕ",
    problemSolving: "ꯋꯥꯈꯜ ꯊꯤꯕ",
    languageCat: "ꯂꯣꯟ",
    motorSpeed: "ꯌꯥꯡꯕ ꯑꯃꯁꯨꯡ ꯈꯣꯡꯖꯦꯜ",
    difficulty: "ꯑꯔꯨꯕ ꯃꯑꯣꯡ",
    easy: "ꯂꯥꯏꯕ",
    medium: "ꯃꯌꯥꯏ ꯑꯣꯏꯕ",
    hard: "ꯑꯔꯨꯕ",
    playGame: "ꯁꯥꯟꯅꯔꯁꯤ",
    score: "ꯁ꯭ꯀꯣꯔ",
    mistakes: "ꯑꯁꯣꯏꯕ",
    accuracy: "ꯆꯨꯝꯕ",
    timeSpent: "ꯃꯇꯝ",
    wellDone: "ꯌꯥꯝꯅ ꯐꯔꯦ!",
    playAgain: "ꯑꯃꯨꯛ ꯁꯥꯟꯅꯕ",
    nextLevel: "ꯃꯊꯪꯒꯤ ꯊꯥꯛ",
    backToGames: "ꯃꯁꯥꯟꯅ ꯄꯔꯤꯡꯗ ꯍꯜꯂꯛꯄ",

    doctorPortalTitle: "ꯗꯣꯛꯇꯔ ꯄꯣꯔꯇꯦꯜ",
    doctorPortalSubtitle: "ꯑꯅꯥꯕꯁꯤꯡꯒꯤ ꯋꯥꯈꯜ ꯍꯛꯁꯦꯜ ꯌꯦꯡꯁꯤꯅꯕ।",
    patientPortalTitle: "ꯗꯣꯛꯇꯔ ꯎꯅꯕ",
    patientPortalSubtitle: "ꯗꯣꯛꯇꯔꯒ ꯍꯛꯊꯦꯡꯅꯅ ꯋꯥꯔꯤ ꯁꯥꯅꯕ।",
    connectedPatients: "ꯁꯝꯅꯔꯕ ꯑꯅꯥꯕꯁꯤꯡ",
    noPatientsYet: "ꯑꯅꯥꯕ ꯑꯃꯠꯇ ꯂꯩꯇ꯭ꯔꯤ।",
    shareDoctorId: "ID ꯑꯁꯤ ꯑꯅꯥꯕꯁꯤꯡꯗ ꯌꯦꯟꯊꯣꯛꯎ",
    myDoctorId: "ꯑꯩꯒꯤ ꯗꯣꯛꯇꯔ ID",
    connectWithDoctor: "ꯗꯣꯛꯇꯔ ID ꯒ ꯁꯝꯅꯕ",
    enterDoctorId: "ꯗꯣꯛꯇꯔ ID ꯏꯌꯨ",
    connectNow: "ꯍꯧꯖꯤꯛ ꯁꯝꯅꯧ",
    connectedDoctor: "ꯁꯝꯅꯔꯕ ꯗꯣꯛꯇꯔ",
    typeMessage: "ꯄꯥꯎꯖꯦꯜ ꯏꯌꯨ...",
    send: "ꯊꯥꯕ",
    cognitiveHistory: "ꯃꯁꯥꯟꯅ ꯄꯨꯋꯥꯔꯤ",
    online: "ꯑꯣꯟꯂꯥꯏꯟ",
    offline: "ꯑꯣꯐꯂꯥꯏꯟ",

    reportTitle: "ꯍꯛꯁꯦꯜ ꯑꯃꯁꯨꯡ ꯋꯥꯈꯜ ꯔꯤꯄꯣꯔꯠ",
    reportSubtitle: "ꯅꯤꯡꯁꯤꯡ ꯁꯛꯇꯤ ꯍꯦꯟꯒꯠꯂꯛꯄꯒꯤ ꯑꯀꯨꯞꯄ ꯋꯥꯔꯣꯜ।",
    overallScore: "ꯑꯄꯨꯟꯕ ꯁ꯭ꯀꯣꯔ",
    gamesPlayed: "ꯁꯥꯟꯅꯈ꯭ꯔꯕ ꯃꯁꯥꯟꯅ",
    retentionAccuracy: "ꯆꯨꯝꯄ ꯆꯥꯡ",
    activeStreak: "ꯅꯨꯃꯤꯠ ꯂꯦꯞꯇꯅ",
    printPdf: "ꯄ꯭ꯔꯤꯟꯠ / PDF",
    domainAverages: "ꯆꯥꯡꯆꯠ",

    profileSettings: "ꯄ꯭ꯔꯣꯐꯥꯏꯜ ꯁꯦꯇꯤꯡꯁ",
    profileSettingsSubtitle: "ꯍꯛꯁꯦꯜ ꯃꯔꯝꯗ ꯑꯃꯁꯨꯡ ꯗꯣꯛꯇꯔ ꯀꯣꯗ ꯌꯦꯡꯁꯤꯅꯕ।",
    fullName: "ꯃꯃꯤꯡ ꯃꯄꯨꯡꯐꯥꯕ",
    mobileNumber: "ꯃꯣꯕꯥꯏꯜ ꯅꯝꯕꯔ",
    email: "ꯏꯃꯦꯜ",
    preferredLanguage: "ꯄꯥꯝꯖꯕ ꯂꯣꯟ",
    emergencyContact: "ꯑꯀꯅꯕ ꯃꯇꯃꯗ ꯀꯧꯅꯕ ꯃꯃꯤꯡ",
    emergencyPhone: "ꯑꯀꯅꯕ ꯐꯣꯟ",
    medicalNotes: "ꯍꯤꯗꯥꯛ-ꯂꯥꯡꯊꯛ ꯅꯣꯠꯁꯤꯡ",
    saveChanges: "ꯊꯝꯃꯨ",

    emergencySosTitle: "ꯑꯀꯅꯕ SOS",
    emergencySosSubtitle: "ꯃꯈꯥꯒꯤ ꯕꯇꯟ ꯑꯁꯤ ꯅꯝꯂꯒ ꯗꯣꯛꯇꯔꯗ ꯑꯀꯅꯕ ꯈꯣꯡꯊꯥꯡ ꯌꯧꯒꯅꯤ।",
    tapToAlert: "ꯑꯀꯅꯕ ꯄꯥꯎ ꯊꯥꯕ",
    alertSentTitle: "ꯗꯣꯛꯇꯔꯗ ꯄꯥꯎ ꯌꯧꯔꯦ!",
    alertSentSubtitle: "ꯅꯍꯥꯛꯀꯤ ꯄꯥꯎ ꯗꯣꯛꯇꯔꯗ ꯊꯥꯈ꯭ꯔꯦ।",
    emergencyHotlines: "ꯑꯀꯅꯕ ꯐꯣꯟ ꯅꯝꯕꯔꯁꯤꯡ",

    welcomeToNeuroSathi: "NeuroSathi ꯗ ꯇꯔꯥꯝꯅ ꯑꯣꯛꯆꯔꯤ",
    authSubtitle: "ꯅꯤꯡꯁꯤꯡ ꯁꯛꯇꯤ ꯌꯦꯡꯁꯤꯅꯕ ꯑꯃꯁꯨꯡ ꯗꯣꯛꯇꯔꯒ ꯁꯝꯅꯕꯒꯤꯗꯃꯛ ꯆꯪꯕꯤꯌꯨ।",
    signIn: "ꯆꯪꯕꯤꯌꯨ (Sign In)",
    signUp: "ꯑꯅꯧꯕ ꯑꯦꯀꯥꯎꯟꯠ",
    phoneOtp: "ꯃꯣꯕꯥꯏꯜ (OTP)",
    emailPassword: "ꯏꯃꯦꯜ ꯑꯃꯁꯨꯡ ꯄꯥꯁꯋꯥꯔꯗ",
    enterMobile: "ꯃꯣꯕꯥꯏꯜ ꯅꯝꯕꯔ ꯏꯌꯨ",
    sendCode: "OTP ꯊꯥꯕ",
    enterOtp: "OTP ꯏꯌꯨ",
    verifyComplete: "ꯂꯣꯏꯁꯤꯜꯂꯣ",
    passwordLabel: "ꯄꯥꯁꯋꯥꯔꯗ",
    specialization: "ꯁ꯭ꯄꯦꯁꯤꯑꯦꯂꯥꯏꯖꯦꯁꯟ",
    hospitalOrClinic: "ꯍꯣꯁꯄꯤꯇꯥꯜ ꯅꯠꯇ꯭ꯔꯒ ꯀ꯭ꯂꯤꯅꯤꯛ",
  },
};

/**
 * Resolves translation for any key given a language name or code.
 * Falls back to English if the translation does not exist in the target language.
 */
export function getTranslation(langCodeOrName: string, key: string): string {
  if (!langCodeOrName) return TRANSLATIONS["en"]?.[key] || key;
  const raw = langCodeOrName.trim().toLowerCase();

  // 1. Direct dictionary match by code
  if (TRANSLATIONS[raw]?.[key]) {
    return TRANSLATIONS[raw][key];
  }

  // 2. Lookup in LANGUAGES_LIST to find corresponding code
  const match = LANGUAGES_LIST.find(
    (l) => l.name.toLowerCase() === raw || l.code.toLowerCase() === raw
  );

  if (match && TRANSLATIONS[match.code]?.[key]) {
    return TRANSLATIONS[match.code][key];
  }

  // 3. Fallback to base code e.g. "hi-IN" -> "hi"
  const prefix = raw.split("-")[0];
  if (TRANSLATIONS[prefix]?.[key]) {
    return TRANSLATIONS[prefix][key];
  }

  // 4. Default to English dictionary or key name
  return TRANSLATIONS["en"]?.[key] || key;
}

/**
 * Returns a list of language codes that currently have complete/dedicated
 * UI dictionaries implemented.
 */
export function getFullyTranslatedUiLanguageCodes(): string[] {
  return ["en", "hi", "as", "bn", "ne", "mni"];
}
